apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastcisearch
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      run: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        run: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
        ports:
        - containerPort: 9200
        env:
        - name: discovery.type
          value: single-node
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Values.namespace }}
  labels:
    run: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
  selector:
    run: elasticsearch

